#!/usr/bin/env bash

archive=$1
[[ $archive == /* ]] || archive=$PWD/$archive
if [[ $archive != *.zip ]]; then
  echo "usage: ${0##*/} 'WORKSPACE Slack export DATE_BEGIN - DATE_END.zip'" >&2
  return 2
fi

outdir=${archive#*.zip}

base=$(readlink -f "$0")
base=${base%/*}

if ! tmpdir=$(mktemp -d) || [[ ! $tmpdir ]]; then
  echo "failed to create a temporary directory" >&2
  return 1
fi
trap -- 'rm -rf "$tmpdir"' EXIT
trap -- 'rm -rf "$tmpdir"; trap - INT; kill -INT $$' INT

echo "base: $base"
echo "archive: $archive"
echo "tmpdir: $tmpdir"
echo "outdir: $outdir"

(cd "$tmpdir" && unzip "$archive") &&
  ( cd "$outdir" &&
      cp "$base/slack-export2html.css" ./ &&
      "$base/slack-export2html.js" "$tmpdir")
